version: '3'
services:
  app:
    build: .
    ports:
      - "9090:9090"
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - ES_INDEX=logs
    volumes:
      - ./logs:/root/logs
    depends_on:
      - mongodb
      - elasticsearch

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  mongo_data:
  es_data: